CREATE TABLE IF NOT EXISTS design_requirements (
    id BIGINT NOT NULL AUTO_INCREMENT,
    requirement_code VARCHAR(30) NULL,
    name VARCHAR(200) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    owner_id VARCHAR(255) NULL,
    owner_name VARCHAR(255) NULL,
    customer_name VARCHAR(255) NULL,
    responsible_id VARCHAR(255) NULL,
    responsible_name VARCHAR(255) NULL,
    responsible_role VARCHAR(255) NULL,
    planner_id VARCHAR(255) NULL,
    planner_name VARCHAR(255) NULL,
    deadline VARCHAR(255) NULL,
    requirements TEXT NULL,
    description TEXT NULL,
    attachments_json LONGTEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_design_requirement_code UNIQUE (requirement_code),
    INDEX idx_design_requirement_status (status),
    INDEX idx_design_requirement_owner (owner_id),
    INDEX idx_design_requirement_planner (planner_id),
    INDEX idx_design_requirement_created (created_at)
);
