package com.emie.designpm.controller;
import com.emie.designpm.entity.*; import com.emie.designpm.service.PerformanceService; import jakarta.servlet.http.HttpServletRequest; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/performance") public class PerformanceController { private final PerformanceService service; public PerformanceController(PerformanceService s){service=s;}
 @GetMapping("/leaderboard") public List<Map<String,Object>> leaderboard(@RequestParam(required=false) String month){return service.leaderboard(month);}
 @GetMapping("/preview") public ResponseEntity<?> preview(@RequestParam(required=false) String userId,@RequestParam(required=false) String month,HttpServletRequest r){AuthController.AuthSession s=session(r);String target="admin".equals(s.role())&&userId!=null&&!userId.isBlank()?userId:s.userId();try{return ResponseEntity.ok(service.preview(target,month));}catch(RuntimeException e){return ResponseEntity.badRequest().body(Map.of("error",e.getMessage()));}}
 @GetMapping("/standard") public ResponseEntity<?> standards(HttpServletRequest r){if(!admin(r))return ResponseEntity.status(403).body(Map.of("error","仅管理员可查看个人标准积分配置"));return ResponseEntity.ok(service.standards());}
 @PutMapping("/standard") public ResponseEntity<?> standard(@RequestBody StandardPointConfig c,HttpServletRequest r){if(!admin(r))return ResponseEntity.status(403).body(Map.of("error","仅管理员可修改配置"));try{return ResponseEntity.ok(service.saveStandard(c));}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body(Map.of("error",e.getMessage()));}}
 @DeleteMapping("/standard/{id}") public ResponseEntity<?> deleteStandard(@PathVariable Long id,HttpServletRequest r){if(!admin(r))return ResponseEntity.status(403).body(Map.of("error","仅管理员可删除配置"));service.deleteStandard(id);return ResponseEntity.ok(Map.of("message","已删除"));}
 @GetMapping("/designer-targets") public ResponseEntity<?> designerTargets(HttpServletRequest r){if(!admin(r))return ResponseEntity.status(403).body(Map.of("error","仅管理员可查看设计师目标"));return ResponseEntity.ok(service.designerTargets(null));}
 @PutMapping("/designer-targets/{userId}") public ResponseEntity<?> designerTarget(@PathVariable String userId,@RequestBody Map<String,Object> body,HttpServletRequest r){AuthController.AuthSession s=session(r);if(!"admin".equals(s.role()))return ResponseEntity.status(403).body(Map.of("error","仅管理员可设置设计师目标"));try{Integer points=body.get("targetPoints") instanceof Number n?n.intValue():null;return ResponseEntity.ok(service.saveDesignerTarget(null,userId,points,s.userId()));}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body(Map.of("error",e.getMessage()));}}
 private boolean admin(HttpServletRequest r){AuthController.AuthSession s=(AuthController.AuthSession)r.getAttribute("authSession");return s!=null&&"admin".equals(s.role());}
 private AuthController.AuthSession session(HttpServletRequest r){AuthController.AuthSession s=(AuthController.AuthSession)r.getAttribute("authSession");if(s==null)throw new IllegalStateException("未登录或会话已过期");return s;}
}
