package com.emie.designpm.controller;
import com.emie.designpm.service.PointProgramOperationsService;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/point-program") public class PointProgramOperationsController{
 private final PointProgramOperationsService service;public PointProgramOperationsController(PointProgramOperationsService s){service=s;}
 @GetMapping("/proposals")ResponseEntity<?>proposals(HttpServletRequest r){return call(()->service.proposals(session(r)));}
 @PostMapping("/proposals")ResponseEntity<?>submit(@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->service.submitProposal(str(b,"title"),str(b,"description"),str(b,"referenceImagesJson"),str(b,"plannedDate"),session(r)));}
 @PostMapping("/proposals/{id}/review")ResponseEntity<?>review(@PathVariable Long id,@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->service.reviewProposal(id,bool(b,"approve"),str(b,"comment"),session(r)));}
 @GetMapping("/forecasts")ResponseEntity<?>forecasts(HttpServletRequest r){return call(()->service.forecasts(session(r)));}
 @PostMapping("/forecasts")ResponseEntity<?>save(@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->service.saveForecast(b.get("id") instanceof Number n?n.longValue():null,str(b,"monthKey"),str(b,"title"),str(b,"description"),str(b,"pointRuleCode"),b.get("estimatedCount") instanceof Number n?n.intValue():null,session(r)));}
 @PostMapping("/forecasts/{id}/publish")ResponseEntity<?>publish(@PathVariable Long id,HttpServletRequest r){return call(()->service.publish(id,session(r)));}
 private AuthController.AuthSession session(HttpServletRequest r){AuthController.AuthSession s=(AuthController.AuthSession)r.getAttribute("authSession");if(s==null)throw new SecurityException("未登录");return s;}private String str(Map<String,Object>b,String k){return b.get(k)==null?null:String.valueOf(b.get(k));}private Long longValue(Map<String,Object>b,String k){if(b.get(k) instanceof Number n)return n.longValue();throw new IllegalArgumentException(k+"不能为空");}private boolean bool(Map<String,Object>b,String k){if(b.get(k) instanceof Boolean x)return x;throw new IllegalArgumentException(k+"必须为布尔值");}private ResponseEntity<?>call(Action a){try{return ResponseEntity.ok(a.run());}catch(SecurityException e){return ResponseEntity.status(403).body(Map.of("error",e.getMessage()));}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body(Map.of("error",e.getMessage()));}catch(IllegalStateException e){return ResponseEntity.status(409).body(Map.of("error",e.getMessage()));}}interface Action{Object run();}
}
