package com.emie.designpm.controller;
import com.emie.designpm.service.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/point-governance") public class PointGovernanceController {
 private final PointAppealService appeals;private final PoPointsService po;private final MonthlyPointArchiveService archives;private final PointManualAdjustmentService manual;
 public PointGovernanceController(PointAppealService a,PoPointsService p,MonthlyPointArchiveService m,PointManualAdjustmentService h){appeals=a;po=p;archives=m;manual=h;}
 @GetMapping("/appeals") public ResponseEntity<?> appeals(HttpServletRequest r){return call(()->appeals.list(session(r)));}
 @PostMapping("/appeals") public ResponseEntity<?> submitAppeal(@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->appeals.submit(longValue(b,"pointLedgerId"),string(b,"type"),string(b,"reason"),doubleValue(b,"correctedScore"),string(b,"attachmentsJson"),session(r)));}
 @PostMapping("/appeals/{id}/planner-process") public ResponseEntity<?> planner(@PathVariable Long id,@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->appeals.plannerProcess(id,string(b,"decision"),string(b,"comment"),session(r)));}
 @PostMapping("/appeals/{id}/admin-review") public ResponseEntity<?> adminReview(@PathVariable Long id,@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->appeals.adminReview(id,string(b,"decision"),string(b,"comment"),doubleValue(b,"adjustmentPoints"),session(r)));}
 @PostMapping("/manual-adjustment") public ResponseEntity<?> manualAdjustment(@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->manual.adjust(string(b,"userId"),integerStrict(b,"points"),string(b,"reason"),session(r)));}
 @PostMapping("/po/projects") public ResponseEntity<?> createPo(@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->po.create(string(b,"name"),string(b,"ownerUserId"),string(b,"ownerName"),integer(b,"monthlyPoints"),session(r)));}
 @GetMapping("/po/me") public ResponseEntity<?> poMine(HttpServletRequest r){return call(()->po.mine(session(r)));}
 @PostMapping("/po/projects/{id}/progress") public ResponseEntity<?> poProgress(@PathVariable Long id,@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->po.submit(id,string(b,"month"),string(b,"summary"),session(r)));}
 @GetMapping("/po/progress") public ResponseEntity<?> poAll(HttpServletRequest r){return call(()->po.all(session(r)));}
 @PostMapping("/po/progress/{id}/review") public ResponseEntity<?> poReview(@PathVariable Long id,@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->po.review(id,booleanValue(b,"approve",true),string(b,"comment"),session(r)));}
 @GetMapping("/archives") public ResponseEntity<?> archiveList(@RequestParam(required=false)String month,HttpServletRequest r){return call(()->archives.list(month,session(r)));}
 @PutMapping("/archives/{month}/{userId}") public ResponseEntity<?> saveArchive(@PathVariable String month,@PathVariable String userId,@RequestBody Map<String,Object>b,HttpServletRequest r){return call(()->archives.save(month,userId,integer(b,"earnedPoints"),integer(b,"targetPoints"),integer(b,"suppliedPoints"),booleanValue(b,"protectionEnabled",false),doubleValue(b,"quarterlyAveragePoints"),session(r)));}
 @PostMapping("/archives/{month}/archive") public ResponseEntity<?> archive(@PathVariable String month,HttpServletRequest r){return call(()->archives.archiveMonth(month,session(r)));}
 @PostMapping("/archives/{month}/prepare") public ResponseEntity<?> prepareArchive(@PathVariable String month,HttpServletRequest r){return call(()->archives.prepare(month,session(r)));}
 private AuthController.AuthSession session(HttpServletRequest r){AuthController.AuthSession s=(AuthController.AuthSession)r.getAttribute("authSession");if(s==null)throw new SecurityException("未登录或会话已过期");return s;}
 private ResponseEntity<?> call(Action a){try{return ResponseEntity.ok(a.run());}catch(SecurityException e){return ResponseEntity.status(403).body(Map.of("error",e.getMessage()));}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body(Map.of("error",e.getMessage()));}catch(IllegalStateException e){return ResponseEntity.status(409).body(Map.of("error",e.getMessage()));}}
 private String string(Map<String,Object>b,String k){Object v=b.get(k);return v==null?null:String.valueOf(v);}private Integer integer(Map<String,Object>b,String k){Object v=b.get(k);return v instanceof Number n?n.intValue():null;}private Integer integerStrict(Map<String,Object>b,String k){Object v=b.get(k);if(v==null)return null;if(v instanceof Number n){double d=n.doubleValue();if(!Double.isFinite(d)||d!=Math.rint(d))throw new IllegalArgumentException(k+"必须为整数");return n.intValue();}throw new IllegalArgumentException(k+"必须为整数");}private Double doubleValue(Map<String,Object>b,String k){Object v=b.get(k);return v instanceof Number n?n.doubleValue():null;}private Long longValue(Map<String,Object>b,String k){Object v=b.get(k);if(v instanceof Number n)return n.longValue();throw new IllegalArgumentException(k+"不能为空");}private Boolean booleanValue(Map<String,Object>b,String k,boolean required){Object v=b.get(k);if(v instanceof Boolean x)return x;if(!required&&v==null)return false;throw new IllegalArgumentException(k+"必须为布尔值");}@FunctionalInterface interface Action{Object run();}
}
