package com.emie.designpm.service;
import com.emie.designpm.controller.AuthController;import com.emie.designpm.entity.MonthlyPointArchive;import com.emie.designpm.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class MonthlyPointArchiveService {
 private final MonthlyPointArchiveRepository archives; private PerformanceService performance; private StandardPointConfigRepository standards; private MonthlyPerformanceConfigRepository months; private MonthlyUserPointTargetRepository userTargets;
 public MonthlyPointArchiveService(MonthlyPointArchiveRepository a){archives=a;}
 @org.springframework.beans.factory.annotation.Autowired void dependencies(PerformanceService p,StandardPointConfigRepository s,MonthlyPerformanceConfigRepository m){performance=p;standards=s;months=m;}
 @org.springframework.beans.factory.annotation.Autowired void monthlyUserTargets(MonthlyUserPointTargetRepository u){userTargets=u;}
 @Transactional public MonthlyPointArchive save(String month,String userId,Integer earned,Integer target,Integer supplied,Boolean protectionEnabled,Double quarterlyAverage,AuthController.AuthSession s){admin(s);month(month);if(blank(userId))throw new IllegalArgumentException("用户不能为空");nonnegative(earned,target,supplied);if(quarterlyAverage==null||quarterlyAverage<0||!Double.isFinite(quarterlyAverage))throw new IllegalArgumentException("季度均值无效");MonthlyPointArchive a=archives.findByMonthKeyAndUserId(month,userId).orElseGet(MonthlyPointArchive::new);if("ARCHIVED".equals(a.getStatus()))throw new IllegalStateException("已归档月份不可修改");a.setMonthKey(month);a.setUserId(userId.trim());a.setEarnedPoints(earned);a.setTargetPoints(target);a.setSuppliedPoints(supplied);a.setInsufficientSupplyProtection(Boolean.TRUE.equals(protectionEnabled)&&supplied<target);a.setQuarterlyAveragePoints(quarterlyAverage);return archives.save(a);}
 @Transactional public List<MonthlyPointArchive> archiveMonth(String month,AuthController.AuthSession s){admin(s);month(month);List<MonthlyPointArchive> list=archives.findByMonthKeyOrderByUserId(month);if(list.isEmpty())throw new IllegalStateException("该月份没有可归档记录");LocalDateTime now=LocalDateTime.now();for(MonthlyPointArchive a:list){if(!"ARCHIVED".equals(a.getStatus())){a.setStatus("ARCHIVED");a.setArchivedBy(s.userId());a.setArchivedAt(now);}}return archives.saveAll(list);}
 // shortage=true 表示当月管理员在月度绩效配置中标记了「供单不足」（monthly_performance_configs.supply_shortage）：
 // 公司当月可供分配的任务量不足，设计师实际达标收益低于承诺目标分值。此时执行供分不足保护——
 // 供分(S)=0、insufficient_supply_protection=true，且当本人连续两月均处于保护且达标率<60% 时，
 // 季度均值按近三月实际得分均值计算，避免单月极端低分被归档锁定为错误数据。
 // P2-2 目标口径统一：管理员在「设计师本月目标」配置的月度目标（monthly_user_point_targets）为权威，与绩效预览一致；未配置的设计师回退个人标准积分（standard_point_configs.points）。
 @Transactional public List<MonthlyPointArchive> prepare(String month,AuthController.AuthSession s){admin(s);month(month);if(performance==null||standards==null||months==null)throw new IllegalStateException("归档计算服务暂不可用");YearMonth ym=YearMonth.parse(month);Map<String,Integer> earned=new HashMap<>();for(Map<String,Object> row:performance.leaderboard(month))earned.put(String.valueOf(row.get("userId")),((Number)row.get("points")).intValue());boolean shortage=months.findByMonthKey(month).map(com.emie.designpm.entity.MonthlyPerformanceConfig::isSupplyShortage).orElse(false);Map<String,Integer> targets=new LinkedHashMap<>();for(com.emie.designpm.entity.StandardPointConfig standard:standards.findAll()){if(!standard.isEnabled())continue;targets.put(standard.getConfigCode(),standard.getPoints());}if(userTargets!=null){for(com.emie.designpm.entity.MonthlyUserPointTarget t:userTargets.findByMonthKeyOrderByUserNameAscUserIdAsc(month))targets.put(t.getUserId(),t.getTargetPoints());}List<MonthlyPointArchive> result=new ArrayList<>();for(Map.Entry<String,Integer> entry:targets.entrySet()){String userId=entry.getKey();int target=entry.getValue();int actual=earned.getOrDefault(userId,0);List<MonthlyPointArchive> previous=new ArrayList<>();for(int offset=1;offset<=2;offset++)archives.findByMonthKeyAndUserId(ym.minusMonths(offset).toString(),userId).ifPresent(previous::add);boolean protectedQuarter=shortage&&target>0&&actual<target*.6&&previous.size()==2&&previous.stream().allMatch(a->Boolean.TRUE.equals(a.getInsufficientSupplyProtection())&&a.getTargetPoints()>0&&a.getEarnedPoints()<a.getTargetPoints()*.6);double average=protectedQuarter?(actual+previous.stream().mapToInt(MonthlyPointArchive::getEarnedPoints).sum())/3d:actual;result.add(save(month,userId,actual,target,shortage?0:target,shortage,average,s));}return result;}
 @Transactional(readOnly=true) public List<MonthlyPointArchive> list(String month,AuthController.AuthSession s){if("admin".equals(PermissionCatalog.normalizeRole(s.role())))return blank(month)?archives.findAll():archives.findByMonthKeyOrderByUserId(month);return archives.findByUserIdOrderByMonthKeyDesc(s.userId());}
 private void admin(AuthController.AuthSession s){if(!"admin".equals(PermissionCatalog.normalizeRole(s.role())))throw new SecurityException("仅管理员可操作");}private void month(String x){try{YearMonth.parse(x);}catch(Exception e){throw new IllegalArgumentException("月份格式应为YYYY-MM");}}private boolean blank(String x){return x==null||x.isBlank();}private void nonnegative(Integer... xs){if(Arrays.stream(xs).anyMatch(x->x==null||x<0))throw new IllegalArgumentException("积分参数不能小于0");}
}
