package com.emie.designpm.service;
import com.emie.designpm.controller.AuthController;import com.emie.designpm.entity.MonthlyPointArchive;import com.emie.designpm.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class MonthlyPointArchiveService {
 private final MonthlyPointArchiveRepository archives; private PerformanceService performance; private StandardPointConfigRepository standards;
 public MonthlyPointArchiveService(MonthlyPointArchiveRepository a){archives=a;}
 @org.springframework.beans.factory.annotation.Autowired void dependencies(PerformanceService p,StandardPointConfigRepository s){performance=p;standards=s;}
 @Transactional public MonthlyPointArchive save(String month,String userId,Integer earned,Integer target,Integer supplied,Boolean protectionEnabled,Double quarterlyAverage,AuthController.AuthSession s){admin(s);month(month);if(blank(userId))throw new IllegalArgumentException("用户不能为空");nonnegative(earned,target,supplied);if(quarterlyAverage==null||quarterlyAverage<0||!Double.isFinite(quarterlyAverage))throw new IllegalArgumentException("季度均值无效");MonthlyPointArchive a=archives.findByMonthKeyAndUserId(month,userId).orElseGet(MonthlyPointArchive::new);if("ARCHIVED".equals(a.getStatus()))throw new IllegalStateException("已归档月份不可修改");a.setMonthKey(month);a.setUserId(userId.trim());a.setEarnedPoints(earned);a.setTargetPoints(target);a.setSuppliedPoints(supplied);a.setInsufficientSupplyProtection(Boolean.TRUE.equals(protectionEnabled)&&supplied<target);a.setQuarterlyAveragePoints(quarterlyAverage);return archives.save(a);}
 @Transactional public List<MonthlyPointArchive> archiveMonth(String month,AuthController.AuthSession s){admin(s);month(month);List<MonthlyPointArchive> list=archives.findByMonthKeyOrderByUserId(month);if(list.isEmpty())throw new IllegalStateException("该月份没有可归档记录");LocalDateTime now=LocalDateTime.now();for(MonthlyPointArchive a:list){if(!"ARCHIVED".equals(a.getStatus())){a.setStatus("ARCHIVED");a.setArchivedBy(s.userId());a.setArchivedAt(now);}}return archives.saveAll(list);}
 @Transactional public List<MonthlyPointArchive> prepare(String month,AuthController.AuthSession s){admin(s);month(month);if(performance==null||standards==null)throw new IllegalStateException("归档计算服务暂不可用");YearMonth ym=YearMonth.parse(month);Map<String,Integer> earned=new HashMap<>();for(Map<String,Object> row:performance.leaderboard(month))earned.put(String.valueOf(row.get("userId")),((Number)row.get("points")).intValue());boolean shortage=false;List<MonthlyPointArchive> result=new ArrayList<>();for(com.emie.designpm.entity.StandardPointConfig standard:standards.findAll()){if(!standard.isEnabled())continue;String userId=standard.getConfigCode();int target=standard.getPoints();int actual=earned.getOrDefault(userId,0);List<MonthlyPointArchive> previous=new ArrayList<>();for(int offset=1;offset<=2;offset++)archives.findByMonthKeyAndUserId(ym.minusMonths(offset).toString(),userId).ifPresent(previous::add);boolean protectedQuarter=shortage&&target>0&&actual<target*.6&&previous.size()==2&&previous.stream().allMatch(a->Boolean.TRUE.equals(a.getInsufficientSupplyProtection())&&a.getTargetPoints()>0&&a.getEarnedPoints()<a.getTargetPoints()*.6);double average=protectedQuarter?(actual+previous.stream().mapToInt(MonthlyPointArchive::getEarnedPoints).sum())/3d:actual;result.add(save(month,userId,actual,target,shortage?0:target,shortage,average,s));}return result;}
 @Transactional(readOnly=true) public List<MonthlyPointArchive> list(String month,AuthController.AuthSession s){if("admin".equals(PermissionCatalog.normalizeRole(s.role())))return blank(month)?archives.findAll():archives.findByMonthKeyOrderByUserId(month);return archives.findByUserIdOrderByMonthKeyDesc(s.userId());}
 private void admin(AuthController.AuthSession s){if(!"admin".equals(PermissionCatalog.normalizeRole(s.role())))throw new SecurityException("仅管理员可操作");}private void month(String x){try{YearMonth.parse(x);}catch(Exception e){throw new IllegalArgumentException("月份格式应为YYYY-MM");}}private boolean blank(String x){return x==null||x.isBlank();}private void nonnegative(Integer... xs){if(Arrays.stream(xs).anyMatch(x->x==null||x<0))throw new IllegalArgumentException("积分参数不能小于0");}
}
