package com.emie.designpm.service;
import com.emie.designpm.controller.AuthController;import com.emie.designpm.entity.*;import com.emie.designpm.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class PointProgramOperationsService{
 private final PointTaskProposalRepository proposals;private final PointTaskForecastRepository forecasts;private final ProjectRepository projects;private final ProjectService projectService;
 public PointProgramOperationsService(PointTaskProposalRepository p,PointTaskForecastRepository f,ProjectRepository projects,ProjectService ps){proposals=p;forecasts=f;this.projects=projects;projectService=ps;}
 @Transactional public PointTaskProposal submitProposal(String title,String description,String referenceImagesJson,String plannedDate,AuthController.AuthSession s){if(!"designer".equals(role(s)))throw new SecurityException("仅设计师可提交自主开发提案");if(blank(title)||blank(description))throw new IllegalArgumentException("提案信息不完整");if(blank(referenceImagesJson)||"[]".equals(referenceImagesJson.trim()))throw new IllegalArgumentException("请至少上传一张设计图");LocalDate.parse(plannedDate);PointTaskProposal p=new PointTaskProposal();p.setApplicantUserId(s.userId());p.setApplicantName(s.name());p.setTitle(cut(title,200));p.setDescription(cut(description,5000));p.setReferenceImagesJson(cut(referenceImagesJson,20000));p.setPlannedDate(plannedDate);return proposals.save(p);}
 @Transactional public PointTaskProposal reviewProposal(Long id,boolean approve,String comment,AuthController.AuthSession s){if(!List.of("planner","admin").contains(role(s)))throw new SecurityException("仅企划或管理员可立项");PointTaskProposal p=proposals.findById(id).orElseThrow(()->new IllegalArgumentException("提案不存在"));if(!"SUBMITTED".equals(p.getStatus()))throw new IllegalStateException("提案已处理");p.setReviewComment(cut(comment,1000));p.setReviewedBy(s.userId());p.setReviewedAt(LocalDateTime.now());if(!approve){p.setStatus("REJECTED");return proposals.save(p);}Map<String,Object>projectBody=new LinkedHashMap<>();projectBody.put("type","regular");projectBody.put("productName",p.getTitle());projectBody.put("deadline",p.getPlannedDate());projectBody.put("productRequirements",p.getDescription());projectBody.put("description","由自主开发提案审核立项");projectBody.put("referenceImagesJson",p.getReferenceImagesJson());projectBody.put("plannerId","planner".equals(role(s))?s.userId():"");projectBody.put("currentRole",role(s));projectBody.put("currentUser",s.name());projectBody.put("currentUserId",s.userId());Project created=projectService.createProject(projectBody);Map<String,Object>taskBody=new LinkedHashMap<>();taskBody.put("name",p.getTitle());taskBody.put("plannedDate",p.getPlannedDate());taskBody.put("workflowStage","design");taskBody.put("designerId",p.getApplicantUserId());taskBody.put("assigneeRole","designer");taskBody.put("details",p.getDescription());taskBody.put("referenceImagesJson",p.getReferenceImagesJson());taskBody.put("assignmentReason","自主开发提案立项："+Optional.ofNullable(comment).orElse("管理层确认"));taskBody.put("selfInitiated",true);taskBody.put("currentRole",role(s));taskBody.put("currentUser",s.name());taskBody.put("currentUserId",s.userId());Project project=projectService.addSubTask(created.getId(),taskBody);Long taskId=project.getTasks().stream().map(SubTask::getId).max(Long::compareTo).orElse(null);p.setProjectId(created.getId());p.setCreatedTaskId(taskId);p.setStatus("APPROVED");return proposals.save(p);}
 @Transactional(readOnly=true)public List<PointTaskProposal>proposals(AuthController.AuthSession s){return List.of("planner","admin").contains(role(s))?proposals.findAllByOrderByCreatedAtDesc():proposals.findByApplicantUserIdOrderByCreatedAtDesc(s.userId());}
 @Transactional public PointTaskForecast saveForecast(Long id,String month,String title,String description,String rule,Integer count,AuthController.AuthSession s){manage(s);YearMonth.parse(month);PointTaskForecast f=id==null?new PointTaskForecast():forecasts.findById(id).orElseThrow(()->new IllegalArgumentException("预测不存在"));if("PUBLISHED".equals(f.getStatus()))throw new IllegalStateException("已发布预测不可直接修改");f.setMonthKey(month);f.setTitle(cut(title,200));f.setDescription(cut(description,5000));f.setPointRuleCode(blank(rule)?null:rule.trim().toUpperCase());f.setEstimatedCount(count==null||count<1?1:count);return forecasts.save(f);}
 @Transactional public PointTaskForecast publish(Long id,AuthController.AuthSession s){manage(s);PointTaskForecast f=forecasts.findById(id).orElseThrow(()->new IllegalArgumentException("预测不存在"));f.setStatus("PUBLISHED");f.setPublishedBy(s.userId());f.setPublishedAt(LocalDateTime.now());return forecasts.save(f);}
 @Transactional(readOnly=true)public List<PointTaskForecast>forecasts(AuthController.AuthSession s){return List.of("planner","admin").contains(role(s))?forecasts.findAllByOrderByMonthKeyDescCreatedAtDesc():forecasts.findByStatusOrderByMonthKeyAscCreatedAtAsc("PUBLISHED");}
 private void manage(AuthController.AuthSession s){if(!List.of("planner","admin").contains(role(s)))throw new SecurityException("仅企划或管理员可维护任务预告");}private String role(AuthController.AuthSession s){return PermissionCatalog.normalizeRole(s.role());}private boolean blank(String x){return x==null||x.isBlank();}private String cut(String x,int n){if(blank(x))throw new IllegalArgumentException("必填内容不能为空");x=x.trim();return x.substring(0,Math.min(n,x.length()));}
}
