package com.emie.designpm.service;
import com.emie.designpm.controller.AuthController;import com.emie.designpm.entity.*;import com.emie.designpm.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class PointProgramOperationsService{
 private final PointTaskForecastRepository forecasts;
 public PointProgramOperationsService(PointTaskForecastRepository f){forecasts=f;}
 @Transactional public PointTaskForecast saveForecast(Long id,String month,String title,String description,String rule,Integer count,AuthController.AuthSession s){manage(s);YearMonth.parse(month);PointTaskForecast f=id==null?new PointTaskForecast():forecasts.findById(id).orElseThrow(()->new IllegalArgumentException("预测不存在"));if("PUBLISHED".equals(f.getStatus()))throw new IllegalStateException("已发布预测不可直接修改");f.setMonthKey(month);f.setTitle(cut(title,200));f.setDescription(cut(description,5000));f.setPointRuleCode(blank(rule)?null:rule.trim().toUpperCase());f.setEstimatedCount(count==null||count<1?1:count);return forecasts.save(f);}
 @Transactional public PointTaskForecast publish(Long id,AuthController.AuthSession s){manage(s);PointTaskForecast f=forecasts.findById(id).orElseThrow(()->new IllegalArgumentException("预测不存在"));f.setStatus("PUBLISHED");f.setPublishedBy(s.userId());f.setPublishedAt(LocalDateTime.now());return forecasts.save(f);}
 @Transactional(readOnly=true)public List<PointTaskForecast>forecasts(AuthController.AuthSession s){return List.of("planner","admin").contains(role(s))?forecasts.findAllByOrderByMonthKeyDescCreatedAtDesc():forecasts.findByStatusOrderByMonthKeyAscCreatedAtAsc("PUBLISHED");}
 private void manage(AuthController.AuthSession s){if(!List.of("planner","admin").contains(role(s)))throw new SecurityException("仅企划或管理员可维护任务预告");}private String role(AuthController.AuthSession s){return PermissionCatalog.normalizeRole(s.role());}private boolean blank(String x){return x==null||x.isBlank();}private String cut(String x,int n){if(blank(x))throw new IllegalArgumentException("必填内容不能为空");x=x.trim();return x.substring(0,Math.min(n,x.length()));}
}
