package com.emie.designpm.service;
import com.emie.designpm.controller.AuthController; import com.emie.designpm.entity.*; import com.emie.designpm.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class PoPointsService {
 private final PoPointProjectRepository projects;private final PoMonthlyProgressRepository progress;private final PoPointLedgerRepository ledgers;private final PointAdjustmentLedgerRepository adjustments;
 public PoPointsService(PoPointProjectRepository p,PoMonthlyProgressRepository g,PoPointLedgerRepository l,PointAdjustmentLedgerRepository a){projects=p;progress=g;ledgers=l;adjustments=a;}
 @Transactional public PoPointProject create(String name,String ownerId,String ownerName,Integer monthlyPoints,AuthController.AuthSession s){admin(s);if(blank(name)||blank(ownerId)||blank(ownerName))throw new IllegalArgumentException("项目名称和负责人不能为空");if(monthlyPoints==null||monthlyPoints<0||monthlyPoints>10000)throw new IllegalArgumentException("月度积分须在0至10000之间");PoPointProject p=new PoPointProject();p.setName(name.trim());p.setOwnerUserId(ownerId.trim());p.setOwnerName(ownerName.trim());p.setMonthlyPoints(monthlyPoints);p.setCreatedBy(s.userId());return projects.save(p);}
 @Transactional public PoMonthlyProgress submit(Long projectId,String month,String summary,AuthController.AuthSession s){PoPointProject p=projects.findById(projectId).orElseThrow(()->new IllegalArgumentException("PO项目不存在"));if(!p.getEnabled())throw new IllegalStateException("PO项目已停用");if(!p.getOwnerUserId().equals(s.userId()))throw new SecurityException("只能提交本人负责的PO项目进展");month(month);if(blank(summary)||summary.trim().length()>4000)throw new IllegalArgumentException("进展说明不能为空且不得超过4000字");if(progress.findByPoProjectIdAndMonthKey(projectId,month).isPresent())throw new IllegalStateException("该月进展已提交");PoMonthlyProgress g=new PoMonthlyProgress();g.setPoProjectId(projectId);g.setMonthKey(month);g.setSummary(summary.trim());g.setSubmittedBy(s.userId());return progress.save(g);}
 @Transactional public PoMonthlyProgress review(Long id,boolean approve,String comment,AuthController.AuthSession s){admin(s);PoMonthlyProgress g=progress.findLockedById(id).orElseThrow(()->new IllegalArgumentException("月度进展不存在"));if(!"SUBMITTED".equals(g.getStatus())){if(approve&&"CONFIRMED".equals(g.getStatus()))return g;throw new IllegalStateException("该进展已处理");}PoPointProject p=projects.findById(g.getPoProjectId()).orElseThrow(()->new IllegalArgumentException("PO项目不存在"));g.setStatus(approve?"CONFIRMED":"REJECTED");g.setConfirmedBy(s.userId());g.setConfirmedAt(LocalDateTime.now());g.setReviewComment(comment==null?null:comment.trim());g=progress.save(g);if(approve&&ledgers.findByProgressId(g.getId()).isEmpty()){PoPointLedger l=new PoPointLedger();l.setProgressId(g.getId());l.setPoProjectId(p.getId());l.setUserId(p.getOwnerUserId());l.setMonthKey(g.getMonthKey());l.setPoints(p.getMonthlyPoints());l.setCreatedBy(s.userId());ledgers.save(l);}if(approve&&adjustments.findBySourceTypeAndSourceId("PO_PROGRESS",g.getId()).isEmpty()){PointAdjustmentLedger x=new PointAdjustmentLedger();x.setUserId(p.getOwnerUserId());x.setSourceType("PO_PROGRESS");x.setSourceId(g.getId());x.setPoints(p.getMonthlyPoints());x.setReason("PO项目月度履职积分："+p.getName()+" "+g.getMonthKey());x.setCreatedBy(s.userId());adjustments.save(x);}return g;}
 @Transactional(readOnly=true) public Map<String,Object> mine(AuthController.AuthSession s){return Map.of("projects",projects.findByOwnerUserIdOrderByIdDesc(s.userId()),"progress",progress.findBySubmittedByOrderBySubmittedAtDesc(s.userId()),"ledger",ledgers.findByUserIdOrderByCreatedAtDesc(s.userId()));}
 @Transactional(readOnly=true) public List<PoMonthlyProgress> all(AuthController.AuthSession s){admin(s);return progress.findAllByOrderBySubmittedAtDesc();}
 private void admin(AuthController.AuthSession s){if(!"admin".equals(PermissionCatalog.normalizeRole(s.role())))throw new SecurityException("仅管理员可操作");}private boolean blank(String x){return x==null||x.isBlank();}private void month(String x){try{YearMonth.parse(x);}catch(Exception e){throw new IllegalArgumentException("月份格式应为YYYY-MM");}}
}
