CREATE TABLE IF NOT EXISTS sub_task_rejection_cycles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    sub_task_id BIGINT NOT NULL,
    sequence_no INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    rejection_role VARCHAR(30) NOT NULL,
    rejected_by_id VARCHAR(255) NULL,
    rejected_by_name VARCHAR(255) NULL,
    rejected_at DATETIME(6) NOT NULL,
    prior_task_status VARCHAR(30) NOT NULL,
    prior_planned_date VARCHAR(255) NULL,
    prior_review_comments TEXT NULL,
    prior_review_snapshot_json LONGTEXT NULL,
    reason TEXT NULL,
    required_completion_date VARCHAR(255) NULL,
    reference_images_json LONGTEXT NULL,
    attachments_json LONGTEXT NULL,
    cancelled_by_id VARCHAR(255) NULL,
    cancelled_by_name VARCHAR(255) NULL,
    cancelled_by_role VARCHAR(255) NULL,
    cancelled_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_sub_task_rejection_cycle UNIQUE (sub_task_id, sequence_no),
    CONSTRAINT fk_rejection_cycle_sub_task FOREIGN KEY (sub_task_id) REFERENCES sub_tasks (id) ON DELETE CASCADE,
    INDEX idx_rejection_cycle_task_status (sub_task_id, status)
);
